### ISSUE TITLE
Create Login page - Front end

### ISSUE THREAD

**Issue by jrsilva** [SJJHINC/SJJH-Base-Project#3]
Gotta create the login page that user's will first see when logged in.

**Comment by s1pham** [comment]
i like to be able to communicate with the either user 
depending on what i need without giving away mycontact infomation
sang pham
 

     On Tuesday, February 3, 2015 5:11 PM, jrsilva <notifications@github.com> wrote:
   

 Gotta create the login page that user's will first see when logged in.—

**Comment by jrsilva** [comment]
This is done- The frontend at least
